name: Code Quality Checks

on:
  pull_request:
    branches:
      - master
      - stage

jobs:
  lint:
    name: Vue and Python linting
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.6'
        architecture: 'x64'
    - uses: actions/setup-node@v1
      with:
        node-version: '12.13.1'
    - name: Install npm and yarn
      run: |
        npm install -g yarn
        yarn install
    - name: Install MySQL Client
      run: sudo apt install default-libmysqlclient-dev
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U pipenv
        pipenv --bare install --dev
    - name: Lint Python with flake8
      run: |
        pipenv run flake8 . --exclude=node_modules --count --select=E9,F63,F7,F82 --show-source --statistics
        pipenv run flake8 . --exclude=node_modules --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run unit tests
      run: SANDBOX_API_URL="${{ secrets.SANDBOX_API_URL }}" pipenv run pytest --verbose
